name: bloc_reno
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  file_picker: ^8.1.4
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.2
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: 0.19.0
  lottie: ^3.1.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  swipe_to: ^1.0.6
  url_launcher: ^6.3.1
  chewie: ^1.8.5
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  google_fonts: ^6.2.1

#  //firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  firebase_ui_auth: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/vectors/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/lottie/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
